### ISSUE TITLE
Todo prep

### ISSUE THREAD

**Issue by willirath** [geomar-tm/visualize-15-million-trajectories#2]
- [ ] prepare examples using pangeo binder
  - [ ] aggregation with data shader (or similar) but with an arbitrary transformation on the color axis

- [ ] challenges
  - [ ] Selection of trajectories (lines!) that pass any given region. Optimization of storage / data handling.
  - [ ] make interactive viz smooth for billions of points (millions are working)
  - [ ] how to aggregate trajectories with, e.g., datashader?
  - [ ] Find clever ways of plotting the data that go beyond just positions.
  - [ ] Use ML / clustering (or similar) to identify (and quantify??) preferred paths
  - [ ] Automatically (?) compare stokes / non-stokes data, e.g., by visually highlighting important aspects of the difference.
